#!/usr/bin/env python3
"""
P11 / R43 — multichannel toy test for prime-shifted strip extension.

Purpose:
- diagnostic only;
- tests the exact pointwise weighted least-squares minimizer for several
  simultaneously active primitive k=1 prime channels at one new-strip point;
- does NOT prove reverse-normal decay or any operator theorem.

The local toy objective is

    F(y) = |y|^2 + sum_p w_p |y + x_p|^2,
    x_p = x(z-log p),
    w_p = (log p)(p-1)p^(-3/2).

Because of the |y|^2 penalty, the exact minimizer is

    y_* = - sum_p w_p x_p / (1 + sum_p w_p).

Writing W=sum w_p and xbar=(sum w_p x_p)/W, the minimum decomposes as

    F(y_*)
      = sum_p w_p |x_p-xbar|^2
        + W/(1+W) |xbar|^2.

Thus prime competition splits into a weighted variance term plus a mean penalty.
The test asks whether weighted averaging alone forces the target O(log U/U) scale.
It does not: coherent/slowly varying data can pass, while oscillatory data can fail
by an O(1) amount after the same weighted-energy normalization.

All primes are generated by a standard-library sieve; no external dependency is used.
"""

from math import cos, exp, floor, log, sqrt


U = 30.0
V = 40.0
Z = 34.0
BAND_CENTERS = (10.0, 12.0, 14.0)
BAND_HALF_WIDTH = 0.15
PROFILE_CENTER = 22.0


def sieve(n: int) -> list[int]:
    flags = bytearray(b"\x01") * (n + 1)
    flags[0:2] = b"\x00\x00"
    m = int(sqrt(n))
    for p in range(2, m + 1):
        if flags[p]:
            start = p * p
            flags[start : n + 1 : p] = b"\x00" * (((n - start) // p) + 1)
    return [p for p in range(2, n + 1) if flags[p]]


def depth(p: int, T: float, u: float) -> int:
    return max(0, floor(2.0 * max(T - abs(u), 0.0) / log(p)))


def weight(p: int) -> float:
    return log(p) * (p - 1) * p ** (-1.5)


def build_records() -> list[tuple[int, float, float, float]]:
    upper = int(exp(max(BAND_CENTERS) + BAND_HALF_WIDTH)) + 2
    primes = sieve(upper)
    records: list[tuple[int, float, float, float]] = []

    for t in BAND_CENTERS:
        lo = exp(t - BAND_HALF_WIDTH)
        hi = exp(t + BAND_HALF_WIDTH)
        band = [p for p in primes if lo <= p <= hi]
        assert band

        for p in band:
            lp = log(p)
            a_p = 0.5 * lp
            residual_output = Z - a_p
            old_endpoint = Z - lp

            # One common new-strip point Z is shared by all channels.
            assert U < Z < V
            assert abs(residual_output) < U
            assert abs(old_endpoint) < U

            # Primitive level 0 is absent at U but resolved at V.
            assert depth(p, U, residual_output) == 0
            assert depth(p, V, residual_output) >= 1

            records.append((p, weight(p), old_endpoint, t))

    return records


def evaluate(records, name: str, profile) -> tuple[float, float, float, float]:
    W = sum(w for _, w, _, _ in records)
    raw = [profile(s) for _, _, s, _ in records]
    weighted_input = sum(w * x * x for (_, w, _, _), x in zip(records, raw))
    assert weighted_input > 0.0

    # Normalize all profiles to the same primitive weighted input energy = 1.
    scale = 1.0 / sqrt(weighted_input)
    xs = [scale * x for x in raw]

    S = sum(w * x for (_, w, _, _), x in zip(records, xs))
    y_star = -S / (1.0 + W)

    minimum = y_star * y_star + sum(
        w * (y_star + x) ** 2 for (_, w, _, _), x in zip(records, xs)
    )

    xbar = S / W
    variance = sum(w * (x - xbar) ** 2 for (_, w, _, _), x in zip(records, xs))
    mean_penalty = (W / (1.0 + W)) * xbar * xbar

    # Exact algebraic decomposition of the pointwise toy minimum.
    assert abs(minimum - (variance + mean_penalty)) < 1e-11

    print(
        f"{name:10s}  min={minimum:.12f}  "
        f"variance={variance:.12f}  mean_penalty={mean_penalty:.12f}  "
        f"y*={y_star:.12f}"
    )
    return minimum, variance, mean_penalty, y_star


def main() -> None:
    records = build_records()
    W = sum(w for _, w, _, _ in records)
    target = log(U) / U

    counts = {
        t: sum(1 for _, _, _, band_t in records if band_t == t)
        for t in BAND_CENTERS
    }

    print("R43 reverse-extension multichannel toy")
    print(f"U={U}, V={V}, z={Z}, target log(U)/U={target:.12f}")
    print(f"band counts={counts}")
    print(f"total primitive weight W={W:.12f}")

    coherent = evaluate(records, "constant", lambda s: 1.0)
    slow = evaluate(records, "slow", lambda s: cos(0.5 * (s - PROFILE_CENTER)))
    medium = evaluate(records, "freq1", lambda s: cos(1.0 * (s - PROFILE_CENTER)))
    fast = evaluate(records, "freq10", lambda s: cos(10.0 * (s - PROFILE_CENTER)))

    # Diagnostic conclusion:
    # coherent/slow data beat the target, but oscillatory data do not.
    assert coherent[0] < target
    assert slow[0] < target
    assert medium[0] > 5.0 * target
    assert fast[0] > 5.0 * target

    print("Conclusion: weighted averaging is coherence-sensitive.")
    print("It can achieve the target scale for coherent band data, but does not")
    print("force O(log U/U) for general weighted-energy-normalized channel data.")
    print("A proof needs an additional variance/coherence estimate across prime shifts.")


if __name__ == "__main__":
    main()
